# -*- coding: utf-8 -*-
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from topiclib import T

Pfx, Sub = "ls", "历史"
def t(slug, typ, domain, g0, g1, name, en, std, desc, *ev):
    return T(Pfx, Sub, slug, typ, domain, g0, g1, name, en, std, desc, *ev)

HS_HISTORY = [
    # 中外历史纲要·中国 OG1 · 年级10
    t("early_state_qin_han_unity", "R", "中外历史纲要·中国", 10, 10, "早期国家与秦汉大一统", "Early state and Qin-Han unity",
      "moe-ls-2017:OG1",
      "能比较夏商周早期国家与秦汉中央集权的治理模型，用出土文献与制度史料分析大一统如何塑造官僚、法律与边疆。",
      "对照分封与郡县的权力结构图", "用一件简牍或石刻说明制度如何运行"),
    t("wei_jin_sui_tang_institutions", "C", "中外历史纲要·中国", 10, 10, "魏晋至隋唐制度文化", "Wei-Jin to Sui-Tang institutions",
      "moe-ls-2017:OG1",
      "能分析门阀政治向科举官僚的转变，比较九品中正、均田、府兵等制度如何回应分裂与再统一。",
      "用制度变迁表解释隋唐重建大一统的条件", "评价士族文化对文学与宗教的影响"),
    t("liao_song_xia_jin_yuan_plural", "C", "中外历史纲要·中国", 10, 10, "辽宋夏金元多元", "Plural regimes Liao to Yuan",
      "moe-ls-2017:OG1",
      "能超越单纯的中原王朝中心叙事，比较多政权并立下的经济、族群与制度互动，分析行省对后世疆域治理的意义。",
      "用互市或和议材料说明政权关系", "评价多元一体格局的史料依据"),
    t("ming_qing_transformation", "C", "中外历史纲要·中国", 10, 10, "明清变局", "Ming-Qing transformation",
      "moe-ls-2017:OG1",
      "能从白银流动、赋役改革、边疆治理与思想转向分析明清的世界位置变化，而不是只记帝王年表。",
      "用一条财政或海外贸易史料解释变局", "比较明清海洋政策的文本与实际执行"),
    t("late_qing_crisis_exploration", "M", "中外历史纲要·中国", 10, 10, "晚清危机与探索", "Late Qing crisis and exploration",
      "moe-ls-2017:OG1",
      "能用条约体系、财政军事危机与思想资源分析洋务、维新、革命等方案的问题意识差异，并检讨冲击—回应模式的局限。",
      "比较两份改革奏折或政论的目标预设", "指出冲击—回应叙事漏掉了哪些内生因素"),
    t("xinhai_republic_transition", "C", "中外历史纲要·中国", 10, 10, "辛亥革命与民国", "1911 Revolution and the Republic",
      "moe-ls-2017:OG1",
      "能分析帝制崩溃后的制度试验、军阀政治与社会动员，用多方史料评估共和转型的连续与断裂。",
      "对照约法文本与实际权力结构", "用报刊材料说明民众对共和的理解差异"),
    t("new_democratic_revolution_path", "C", "中外历史纲要·中国", 10, 10, "新民主主义革命道路", "New democratic revolution path",
      "moe-ls-2017:OG1",
      "能比较城市中心与农村包围城市两条路径的条件，用会议文献与地方史料分析统一战线、武装斗争和党建。",
      "用一份会议决议说明战略转折", "评价把革命简化为若干战役的叙述"),
    t("socialist_revolution_construction", "C", "中外历史纲要·中国", 10, 10, "社会主义革命与建设", "Socialist revolution and construction",
      "moe-ls-2017:OG1",
      "能分析三大改造、计划经济与工业化战略的成效与代价，用统计与亲历材料做有限度的历史评估。",
      "比较一五计划目标与产业结构变化", "指出一种只颂扬或只否定的评价问题"),
    t("reform_era_new_period", "C", "中外历史纲要·中国", 10, 10, "改革开放新时期", "Reform and opening period",
      "moe-ls-2017:OG1",
      "能把家庭联产承包、特区试验、市场取向改革等节点放入国内外环境中分析，说明道路探索的阶段性。",
      "用一组宏观数据解释增长与结构转型", "比较渐进改革与休克疗法的历史语境"),
    t("new_era_historical_position", "M", "中外历史纲要·中国", 10, 10, "新时代历史方位", "New era historical position",
      "moe-ls-2017:OG1",
      "能从主要矛盾变化、全面小康与民族复兴目标讨论历史分期，用政策文献与社会变迁材料说明连续和差异。",
      "说明新时代与改革开放前期的连续和差异", "评价一种把当代史写成宣传年表的做法"),

    # 中外历史纲要·世界 OG2 · 年级11
    t("ancient_civ_comparative_models", "P", "中外历史纲要·世界", 11, 11, "古代文明比较", "Ancient civilizations compared",
      "moe-ls-2017:OG2",
      "能用生态环境、国家形态、文字宗教等维度比较大河文明与古典地中海文明，避免单线进化叙事。",
      "完成一份跨文明比较矩阵", "指出地理决定论在解释上的漏洞"),
    t("medieval_world_systems", "C", "中外历史纲要·世界", 11, 11, "中古世界体系", "Medieval world systems",
      "moe-ls-2017:OG2",
      "能把伊斯兰世界、欧洲封建、东亚朝贡、印度洋贸易放入相互联系的中古世界，分析跨区域网络如何运转。",
      "在地图上标出一条跨洲商品或知识路线", "比较两种中古政治合法性来源"),
    t("west_rise_colonialism_sources", "M", "中外历史纲要·世界", 11, 11, "西方兴起与殖民", "Western rise and colonialism",
      "moe-ls-2017:OG2",
      "能辨析大航海、军事财政国家与殖民掠夺在西方兴起中的权重，并评估殖民地视角下的世界史写法。",
      "用一份殖民档案与一份本地记载对照同一事件", "评价西方中心论的史料问题"),
    t("industrial_rev_capitalism", "C", "中外历史纲要·世界", 11, 11, "工业革命与资本主义", "Industrial revolution and capitalism",
      "moe-ls-2017:OG2",
      "能分析技术、能源、工厂制度与世界市场如何相互强化，比较工业化的社会代价与全球分工。",
      "用生产与贸易数据说明世界市场形成", "评价社会立法或工人运动的历史含义"),
    t("socialist_movement_russian_rev", "C", "中外历史纲要·世界", 11, 11, "社会主义运动与俄国革命", "Socialist movement and Russian Revolution",
      "moe-ls-2017:OG2",
      "能把国际工人运动到十月革命放入资本主义危机与战争背景，比较改良与革命道路及俄国条件的特殊性。",
      "对照宣言的问题意识与一九一七年局势", "分析苏维埃政权的制度创新与困境"),
    t("two_world_wars_order", "C", "中外历史纲要·世界", 11, 11, "两次世界大战与秩序", "World wars and international order",
      "moe-ls-2017:OG2",
      "能比较凡尔赛—华盛顿体系与雅尔塔体系的设计逻辑，分析战争、经济危机与意识形态如何重塑秩序。",
      "用条约条款说明秩序安排的内在矛盾", "评价把大战胜利简化为少数战役的说法"),
    t("cold_war_to_multipolarity", "C", "中外历史纲要·世界", 11, 11, "冷战与多极化", "Cold War and multipolarity",
      "moe-ls-2017:OG2",
      "能分析两极对峙、第三世界不结盟与区域一体化如何同时展开，解释冷战后多极化趋势的历史根源。",
      "用一次危机说明核威慑下的决策约束", "比较两极解体后的几种秩序想象"),
    t("contemporary_global_challenges", "C", "中外历史纲要·世界", 11, 11, "当代全球挑战", "Contemporary global challenges",
      "moe-ls-2017:OG2",
      "能把气候、疫情、数字鸿沟、地区冲突作为相互关联的全球史议题，评估国际组织与主权国家的治理张力。",
      "用两则不同来源材料评估同一全球议题", "提出有历史依据的治理比较"),

    # 国家制度与社会治理 S1 · 年级12
    t("ancient_exam_and_law", "C", "国家制度与社会治理", 12, 12, "中国古代选官与法治", "Ancient selection and law",
      "moe-ls-2017:S1",
      "能比较察举、九品、科举的社会效果，分析律令体制与礼治如何共同塑造治理，避免用专制一词代替分析。",
      "用一部法典残篇说明罪刑逻辑", "评价科举对社会流动的双重作用"),
    t("modern_political_systems_compare", "P", "国家制度与社会治理", 12, 12, "近代政治体制比较", "Modern political systems compared",
      "moe-ls-2017:S1",
      "能比较君主立宪、共和、苏维埃等体制在近代中国与世界的移植与变异，分析制度文本与运行的落差。",
      "对照两部宪法性文件的权力结构", "说明为何同样标签下实践差异巨大"),
    t("modern_state_governance", "C", "国家制度与社会治理", 12, 12, "现代国家治理", "Modern state governance",
      "moe-ls-2017:S1",
      "能用科层、法治、技术治理等概念分析二十世纪国家能力扩张，比较动员型与常规型治理。",
      "用一项公共工程说明现代国家的组织方式", "评价技术监控与权利保障的张力"),
    t("grassroots_governance_history", "C", "国家制度与社会治理", 12, 12, "基层治理历史", "History of grassroots governance",
      "moe-ls-2017:S1",
      "能追溯乡里、保甲、公社、社区等基层组织变迁，分析国家权力下沉与地方自治的历史摆动。",
      "用一份地方档案说明基层如何执行政策", "比较两个时期乡村治理的权责结构"),
    t("intl_law_and_sovereignty", "C", "国家制度与社会治理", 12, 12, "国际法与主权", "International law and sovereignty",
      "moe-ls-2017:S1",
      "能从近代主权规范演变分析不平等条约体系对主权的冲击与回收，评估把主权视为过时概念的历史语境。",
      "用一条国际法原则分析一则领土或海洋争议表述", "评价主权过时论所忽略的历史经验"),

    # 经济与社会生活 S2 · 年级12
    t("agrarian_and_commerce_ancient", "C", "经济与社会生活", 12, 12, "古代农耕与工商业", "Ancient farming and commerce",
      "moe-ls-2017:S2",
      "能分析小农经济与市镇、漕运、手工业的互补，评估重农抑商口号与实际商业发展之间的距离。",
      "用物价或商税材料说明市场活跃度", "比较江南与华北经济结构"),
    t("modern_economic_structure_shift", "R", "经济与社会生活", 12, 12, "近代经济结构变动", "Modern economic structural change",
      "moe-ls-2017:S2",
      "能用海关统计、口岸贸易与乡村手工业材料分析自然经济分解与二元结构，避免把近代经济写成单线衰落。",
      "解读一组进出口结构数据", "评价买办、民族资本与外资的复杂关系"),
    t("industrialization_urbanization_hist", "C", "经济与社会生活", 12, 12, "工业化与城市化", "Industrialization and urbanization",
      "moe-ls-2017:S2",
      "能比较不同国家工业化路径与城市社会问题，分析中国近现代城市化的节奏、空间与阶层。",
      "用城市人口与产业数据说明阶段特征", "评价贫民窟或单位大院作为社会史证据"),
    t("social_security_history", "C", "经济与社会生活", 12, 12, "社会保障史", "History of social security",
      "moe-ls-2017:S2",
      "能追溯济贫、互助、社会保险的制度谱系，比较不同保障模式所依赖的财政与政治条件。",
      "对照两份保障法规的覆盖范围", "分析战争或危机如何推动制度创新"),
    t("everyday_life_change", "P", "经济与社会生活", 12, 12, "日常生活变迁", "Everyday life change",
      "moe-ls-2017:S2",
      "能从饮食、服饰、媒介、家庭结构切入长时段社会史，用口述与器物补文献之不足。",
      "用一件日常器物做社会史解读", "比较两代人时间安排变化的含义"),

    # 文化交流与传播 S3 · 年级12
    t("chinese_civ_external_exchange", "C", "文化交流与传播", 12, 12, "中华文明对外交流", "Chinese civilization in exchange",
      "moe-ls-2017:S3",
      "能分析朝贡、佛教东传、技术西传等机制，评估交流中的选择、改造与误读，而不是开列输出输入清单。",
      "用一件外来文物说明本土化过程", "评价丝绸之路叙事的史料边界"),
    t("world_religion_diffusion", "R", "文化交流与传播", 12, 12, "世界宗教传播", "World religion diffusion",
      "moe-ls-2017:S3",
      "能比较佛教、基督教、伊斯兰教的传播路径与本土化策略，分析宗教与帝国、商路的关系。",
      "在地图上标出一条宗教传播走廊", "用一则译经或改宗材料说明文化转译"),
    t("modern_western_learning_east", "L", "文化交流与传播", 12, 12, "近代西学东渐", "Modern Western learning eastward",
      "moe-ls-2017:S3",
      "能分析译介制度、新式学堂与报刊如何改变知识权力，比较中体西用与更激进文化方案的概念选择。",
      "对照两种译本或教科书的关键词", "评价科学话语如何进入政治论争"),
    t("global_cultural_interaction", "M", "文化交流与传播", 12, 12, "全球文化互动", "Global cultural interaction",
      "moe-ls-2017:S3",
      "能用文化流动、混杂与文化霸权等概念分析电影、体育、饮食的全球史，警惕文明冲突的简化模型。",
      "分析一个全球流行文化在中国的接受差异", "评价文化全球化是否等于同质化"),
]
