# -*- coding: utf-8 -*-
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from topiclib import T

HISTORY = [
    T("ls", "历史", "bronze_culture_shang", "C", "中国古代史", 7, 7, "商代青铜文明", "Shang bronze culture", "moe-ls-2022:CN.ANC", "了解商代青铜器与甲骨文，知道它们是研究商史的重要证据。", '描述司母戊鼎的特点', '辨认几个常见甲骨文'),
    T("ls", "历史", "han_silk_road", "C", "中国古代史", 7, 8, "汉代与丝绸之路", "Han Silk Road", "moe-ls-2022:CN.ANC", "知道张骞通西域开辟丝绸之路，促进中外经济文化交流。", '在地图上标出丝绸之路路线', '举一例传入中国的作物'),
    T("ls", "历史", "qin_unification", "C", "中国古代史", 7, 7, "秦统一六国", "Qin unification", "moe-ls-2022:CN.ANC", "了解秦始皇统一文字、货币、度量衡，建立中央集权制度。", '列举三项统一措施', '解释郡县制与分封制区别'),
    T("ls", "历史", "tang_golden_age", "C", "中国古代史", 7, 8, "盛唐气象", "Tang golden age", "moe-ls-2022:CN.ANC", "了解唐代开放繁荣，能举例说明诗歌、艺术与国际交往。", '背诵或解读一首唐诗背景', '说明长安的国际地位'),
    T("ls", "历史", "xia_shang_zhou_timeline", "C", "中国古代史", 7, 7, "夏商周三代概览", "Xia Shang Zhou", "moe-ls-2022:CN.ANC", "知道夏、商、西周是我国早期王朝，能按时间顺序排列三代重大事件。", '排列禹、汤、武王相关事件', '在年表上标出三代起止'),
    T("ls", "历史", "zhou_feudal_system", "C", "中国古代史", 7, 7, "西周分封制", "Zhou feudal system", "moe-ls-2022:CN.ANC", "知道周天子分封诸侯，理解分封制对早期政治格局的影响。", '画出简化的分封示意图', '说明诸侯对天子的义务'),
    T("ls", "历史", "great_wall_function", "C", "中国古代史", 8, 9, "长城与防御体系", "Great Wall", "moe-ls-2022:CN.ANC", "知道长城历代修建与军事防御功能，理解其象征意义。", '区分秦长城与明长城', '讨论长城的历史文化价值'),
    T("ls", "历史", "ming_zhenghe_voyage", "C", "中国古代史", 8, 8, "明代郑和下西洋", "Zheng He voyages", "moe-ls-2022:CN.ANC", "知道郑和七次下西洋的时间、目的及中外交往意义。", '列出郑和船队到达的地区', '比较中外航海的不同目的'),
    T("ls", "历史", "qing_frontier_governance", "C", "中国古代史", 8, 9, "清代边疆治理", "Qing frontiers", "moe-ls-2022:CN.ANC", "了解清朝巩固边疆举措，知道台湾、西藏、新疆隶属中央的历史。", '说明驻藏大臣的职责', '梳理台湾归属沿革'),
    T("ls", "历史", "song_economy_culture", "C", "中国古代史", 8, 8, "宋代经济与文化", "Song economy", "moe-ls-2022:CN.ANC", "知道宋代商业与城市发达，科技发明如活字印刷影响深远。", '说明交子出现的意义', '介绍毕昇活字印刷'),
    T("ls", "历史", "yuan_multicultural", "C", "中国古代史", 8, 8, "元朝辽阔疆域", "Yuan empire", "moe-ls-2022:CN.ANC", "了解元朝统一多民族国家格局，知道行省制度对后世影响。", '在地图指出元朝疆域范围', '解释行省制度作用'),
    T("ls", "历史", "confucius_and_education", "C", "中国古代史", 9, 9, "孔子与儒家教育", "Confucius education", "moe-ls-2022:CN.ANC", "了解孔子生平和有教无类思想，知道儒家对古代教育的影响。", '解释论语名句的含义', '比较古代科举与今天升学'),
    T("ls", "历史", "opium_war_1840", "C", "中国近代史", 7, 7, "鸦片战争与开端", "Opium War 1840", "moe-ls-2022:CN.MOD", "知道1840年鸦片战争是中国近代史开端，理解主权遭破坏的开始。", '列出战争主要结果', '说明《南京条约》割地赔款'),
    T("ls", "历史", "self_strengthening", "C", "中国近代史", 7, 8, "洋务运动", "Self-Strengthening Movement", "moe-ls-2022:CN.MOD", "了解洋务派办军工民用企业，认识“师夷长技”的局限与作用。", '列举江南制造总局等洋务企业', '评价洋务运动成败'),
    T("ls", "历史", "taiping_heavenly", "C", "中国近代史", 7, 8, "太平天国运动", "Taiping Rebellion", "moe-ls-2022:CN.MOD", "知道太平天国反抗封建统治与外国侵略，认识农民战争的历史作用。", '简述《天朝田亩制度》主张', '分析运动失败原因'),
    T("ls", "历史", "unequal_treaties", "C", "中国近代史", 7, 7, "不平等条约体系", "Unequal treaties", "moe-ls-2022:CN.MOD", "了解列强通过条约攫取通商、领事裁判等特权，中国沦为半殖民地。", '归纳条约常见条款类型', '在地图上标出通商口岸'),
    T("ls", "历史", "1911_revolution", "C", "中国近代史", 8, 8, "辛亥革命", "1911 Revolution", "moe-ls-2022:CN.MOD", "知道辛亥革命推翻清朝、建立中华民国，结束两千多年君主专制。", '说明武昌起义过程', '评价辛亥革命历史意义'),
    T("ls", "历史", "boxer_anti_imperialist", "C", "中国近代史", 8, 8, "义和团反帝斗争", "Boxer Movement", "moe-ls-2022:CN.MOD", "了解义和团反帝爱国性质，认识中外反动势力联合镇压的结果。", '说明义和团口号含义', '梳理八国联军侵华影响'),
    T("ls", "历史", "cpc_founding_1921", "C", "中国近代史", 8, 9, "中国共产党成立", "CPC founding 1921", "moe-ls-2022:CN.MOD", "知道1921年中国共产党诞生是中国历史开天辟地大事。", '说出中共一大召开地点', '解释建党的历史必然'),
    T("ls", "历史", "hundred_days_reform", "C", "中国近代史", 8, 8, "戊戌变法", "Hundred Days Reform", "moe-ls-2022:CN.MOD", "知道康有为、梁启超推动维新变法，理解变法图强与保守势力冲突。", '列出变法主要措施', '分析变法失败原因'),
    T("ls", "历史", "long_march_spirit", "C", "中国近代史", 8, 9, "红军长征", "Long March", "moe-ls-2022:CN.MOD", "了解红军长征历程，理解遵义会议转折意义和长征精神。", '在地图标出长征主要路线', '概括长征精神内涵'),
    T("ls", "历史", "may_fourth_movement", "C", "中国近代史", 8, 9, "五四运动", "May Fourth Movement", "moe-ls-2022:CN.MOD", "了解五四运动反帝反封建性质，知道它促进马克思主义传播。", '分析“外争主权内除国贼”', '列举运动代表人物'),
    T("ls", "历史", "anti_japanese_war", "C", "中国近代史", 9, 9, "抗日战争", "Anti-Japanese War", "moe-ls-2022:CN.MOD", "知道全民族抗战历程，理解中国人民是抗战胜利的中流砥柱。", '列举正面与敌后战场战例', '说明抗战胜利伟大意义'),
    T("ls", "历史", "liberation_war_1949", "C", "中国近代史", 9, 9, "解放战争与建国", "Liberation War", "moe-ls-2022:CN.MOD", "了解三大战役与渡江战役，知道1949新中国成立的历史意义。", '排列解放战争关键节点', '解释新民主主义革命胜利'),
    T("ls", "历史", "land_reform_industry", "C", "中国现代史", 8, 9, "土地改革与工业化", "Land reform and industry", "moe-ls-2022:CN.CON", "了解土地改革解放生产力，一五计划奠定工业化基础。", '说明土地改革对农民意义', '列举一五计划重点工程'),
    T("ls", "历史", "prc_founding_1949", "C", "中国现代史", 8, 8, "中华人民共和国成立", "PRC founding", "moe-ls-2022:CN.CON", "知道1949年10月1日开国大典，理解中国人民站起来的含义。", '描述开国大典主要场景', '比较新旧中国政权性质'),
    T("ls", "历史", "new_era_missions", "M", "中国现代史", 9, 9, "新时代历史使命", "New era missions", "moe-ls-2022:CN.CON", "知道中国特色社会主义进入新时代，理解第二个百年奋斗目标。", '写出两个一百年目标', '联系自身谈使命担当'),
    T("ls", "历史", "one_country_two_systems", "C", "中国现代史", 9, 9, "一国两制与统一", "One country two systems", "moe-ls-2022:CN.CON", "知道“一国两制”方针，了解香港、澳门回归祖国历程。", '说明港澳回归时间', '解释一国两制基本内涵'),
    T("ls", "历史", "poverty_alleviation", "C", "中国现代史", 9, 9, "脱贫攻坚成就", "Poverty alleviation", "moe-ls-2022:CN.CON", "了解新时代脱贫攻坚全面胜利，理解以人民为中心的发展思想。", '列举脱贫典型做法', '讨论共同富裕目标'),
    T("ls", "历史", "reform_opening_1978", "C", "中国现代史", 9, 9, "改革开放决策", "Reform opening 1978", "moe-ls-2022:CN.CON", "知道十一届三中全会开启改革开放，理解工作重心转移。", '解释家庭联产承包责任制', '举例经济特区的作用'),
    T("ls", "历史", "socialism_modernization", "C", "中国现代史", 9, 9, "社会主义现代化建设", "Modernization drive", "moe-ls-2022:CN.CON", "了解改革开放以来经济、科技、国防等现代化成就。", '用实例说明高铁或航天成就', '讨论现代化与人民生活'),
    T("ls", "历史", "socialism_system_advantage", "C", "中国现代史", 9, 9, "中国特色社会主义制度优势", "System advantages", "moe-ls-2022:CN.CON", "通过抗疫、救灾等实例，理解集中力量办大事的制度优势。", '分析一次重大工程组织方式', '比较中外应对危机差异'),
    T("ls", "历史", "ancient_greece_democracy", "C", "世界古代史", 7, 8, "古希腊民主政治", "Ancient Greek democracy", "moe-ls-2022:WD.ANC", "知道雅典城邦民主政治特点，理解其对西方政治文化影响。", '比较雅典公民与非公民', '评价雅典民主局限'),
    T("ls", "历史", "indus_ganges_civilization", "C", "世界古代史", 7, 7, "古印度文明", "Ancient India", "moe-ls-2022:WD.ANC", "了解印度河流域文明与种姓制度，知道佛教起源与传播。", '简述种姓制度层级', '说明佛教传播路径'),
    T("ls", "历史", "mesopotamia_egypt", "C", "世界古代史", 7, 7, "两河流域与古埃及", "Mesopotamia and Egypt", "moe-ls-2022:WD.ANC", "知道古巴比伦、古埃及文明出现较早，了解金字塔与汉谟拉比法典。", '比较两大文明河流环境', '说明法典的历史价值'),
    T("ls", "历史", "rome_law_empire", "C", "世界古代史", 7, 8, "古罗马法律与帝国", "Roman law and empire", "moe-ls-2022:WD.ANC", "了解罗马法对后世法律影响，知道罗马帝国扩张与衰亡。", '解释《十二铜表法》意义', '在地图标出罗马帝国疆域'),
    T("ls", "历史", "ancient_civilization_comparison", "M", "世界古代史", 8, 9, "古代文明比较", "Ancient civilizations compare", "moe-ls-2022:WD.ANC", "能从大河、海洋等角度比较古代文明产生条件与成就。", '完成文明特征对照表', '讨论地理环境对文明影响'),
    T("ls", "历史", "islamic_golden_age", "C", "世界古代史", 8, 8, "阿拉伯帝国与文化", "Islamic golden age", "moe-ls-2022:WD.ANC", "知道阿拉伯帝国促进东西方文化交流，保存并传播科学知识。", '举例阿拉伯数字传播', '说明驿站对交流作用'),
    T("ls", "历史", "medieval_europe_feudal", "C", "世界古代史", 8, 8, "中世纪欧洲封建", "Medieval feudal Europe", "moe-ls-2022:WD.ANC", "了解西欧封建等级制度与庄园经济，知道基督教会的影响。", '画出封建等级金字塔', '说明庄园自给自足'),
    T("ls", "历史", "silk_road_world_link", "C", "世界古代史", 8, 9, "古代世界联系", "Ancient world links", "moe-ls-2022:WD.ANC", "知道欧亚非古代存在贸易与文化传播，丝绸之路是重要纽带。", '标出主要商路', '举一例技术西传或东传'),
    T("ls", "历史", "african_kingdoms", "C", "世界古代史", 9, 9, "古代非洲文明", "Ancient African kingdoms", "moe-ls-2022:WD.ANC", "知道古代非洲存在马里等王国，了解其贸易与文化成就。", '在地图标出主要王国', '说明撒哈拉贸易路线'),
    T("ls", "历史", "japanese_ancient_state", "C", "世界古代史", 9, 9, "古代日本大化改新", "Ancient Japan reform", "moe-ls-2022:WD.ANC", "了解大化改新学习隋唐制度，知道日本古代国家形成过程。", '比较大化改新与中国制度', '说明遣唐使作用'),
    T("ls", "历史", "enlightenment_ideas", "C", "世界近代史", 7, 8, "启蒙运动思想", "Enlightenment", "moe-ls-2022:WD.MOD", "知道伏尔泰、卢梭等启蒙思想家，理解理性、自由平等观念。", '概括启蒙思想对革命影响', '比较启蒙与文艺复兴'),
    T("ls", "历史", "geographic_discoveries", "C", "世界近代史", 7, 7, "新航路开辟", "Age of Discovery", "moe-ls-2022:WD.MOD", "了解哥伦布、麦哲伦等航行，知道新航路开辟改变世界格局。", '在地图标出主要航线', '分析殖民扩张双重影响'),
    T("ls", "历史", "industrial_revolution", "C", "世界近代史", 7, 8, "工业革命", "Industrial Revolution", "moe-ls-2022:WD.MOD", "了解蒸汽机、工厂制度等变革，认识工业革命推动城市化。", '列举三项工业革命发明', '分析工业化社会影响'),
    T("ls", "历史", "renaissance_humanism", "C", "世界近代史", 7, 7, "文艺复兴人文主义", "Renaissance", "moe-ls-2022:WD.MOD", "知道文艺复兴兴起于意大利，人文主义反对神权，促进思想解放。", '介绍一位文艺复兴代表', '说明人文主义核心主张'),
    T("ls", "历史", "american_independence", "C", "世界近代史", 8, 8, "美国独立战争", "American Revolution", "moe-ls-2022:WD.MOD", "知道1776年《独立宣言》，了解美国摆脱殖民统治建立共和制。", '说明独立战争原因', '解释《独立宣言》原则'),
    T("ls", "历史", "french_revolution", "C", "世界近代史", 8, 8, "法国大革命", "French Revolution", "moe-ls-2022:WD.MOD", "了解攻占巴士底狱、《人权宣言》，认识革命打击封建制度。", '排列革命主要阶段', '评价《人权宣言》意义'),
    T("ls", "历史", "imperialism_division", "C", "世界近代史", 8, 9, "资本主义进入帝国主义", "Imperialism", "moe-ls-2022:WD.MOD", "了解19世纪末列强瓜分世界，认识殖民体系形成。", '在地图标出主要殖民地', '分析帝国主义矛盾'),
    T("ls", "历史", "marxism_birth", "C", "世界近代史", 8, 9, "马克思主义诞生", "Marxism birth", "moe-ls-2022:WD.MOD", "知道1848年《共产党宣言》发表，了解科学社会主义基本原理。", '解释剩余价值概念入门', '说明马克思主义传播'),
    T("ls", "历史", "japan_meiji_restoration", "C", "世界近代史", 9, 9, "日本明治维新", "Meiji Restoration", "moe-ls-2022:WD.MOD", "知道日本通过明治维新走上资本主义道路，对外扩张。", '列举维新主要措施', '评价维新成败'),
    T("ls", "历史", "latin_america_independence", "C", "世界近代史", 9, 9, "拉丁美洲独立运动", "Latin American independence", "moe-ls-2022:WD.MOD", "了解玻利瓦尔等领导独立斗争，认识民族解放运动。", '在地图标出独立国家', '比较拉美与北美独立'),
    T("ls", "历史", "scientific_revolution", "C", "世界近代史", 9, 9, "近代科学革命", "Scientific revolution", "moe-ls-2022:WD.MOD", "知道牛顿、达尔文等科学成就，理解科学推动社会变革。", '说明万有引力或进化论影响', '讨论科学与人文关系'),
    T("ls", "历史", "world_market_formation", "C", "世界近代史", 9, 9, "世界市场形成", "World market", "moe-ls-2022:WD.MOD", "理解工业革命与新航路如何促成全球贸易体系。", '绘制世界市场形成流程图', '举例一种全球商品流动'),
    T("ls", "历史", "great_depression", "C", "世界现代史", 8, 9, "1929经济大危机", "Great Depression", "moe-ls-2022:WD.CON", "了解资本主义世界经济危机，知道罗斯福新政等应对。", '说明危机表现', '比较新政与传统自由放任'),
    T("ls", "历史", "russian_revolution", "C", "世界现代史", 8, 8, "俄国十月革命", "October Revolution", "moe-ls-2022:WD.CON", "知道1917年十月革命建立第一个社会主义国家，开辟新道路。", '排列俄国革命阶段', '解释苏维埃政权特点'),
    T("ls", "历史", "ww1_causes", "C", "世界现代史", 8, 8, "第一次世界大战", "World War I", "moe-ls-2022:WD.CON", "了解一战爆发原因、主要战场与凡尔赛体系，认识战争灾难。", '分析帝国主义矛盾', '说明凡尔赛条约问题'),
    T("ls", "历史", "cold_war_bipolar", "C", "世界现代史", 9, 9, "冷战与两极格局", "Cold War", "moe-ls-2022:WD.CON", "了解美苏冷战对峙，知道两极格局对世界政治的影响。", '区分冷战与热战', '说明柏林墙象征意义'),
    T("ls", "历史", "decolonization_wave", "C", "世界现代史", 9, 9, "亚非拉民族独立浪潮", "Decolonization", "moe-ls-2022:WD.CON", "知道二战后殖民体系瓦解，亚非拉国家纷纷独立。", '在地图标出独立国家', '分析万隆会议意义'),
    T("ls", "历史", "globalization_trends", "C", "世界现代史", 9, 9, "经济全球化", "Globalization", "moe-ls-2022:WD.CON", "了解冷战后经济全球化加深，认识机遇与挑战并存。", '举例跨国公司与互联网', '讨论全球化对就业影响'),
    T("ls", "历史", "human_rights_development", "C", "世界现代史", 9, 9, "现代人权发展", "Human rights", "moe-ls-2022:WD.CON", "知道《世界人权宣言》等文件，理解人权进步与各国差异。", '概括宣言核心权利', '比较历史中人权状况'),
    T("ls", "历史", "tech_revolution_info", "C", "世界现代史", 9, 9, "信息时代变革", "Information age", "moe-ls-2022:WD.CON", "了解第三次科技革命，认识信息技术对生产生活的改变。", '列举信息技术应用', '讨论数字鸿沟问题'),
    T("ls", "历史", "united_nations", "C", "世界现代史", 9, 9, "联合国与战后秩序", "United Nations", "moe-ls-2022:WD.CON", "知道1945年联合国成立，理解维护和平、促进发展的宗旨。", '列举联合国主要机构', '举例联合国维和行动'),
    T("ls", "历史", "ww2_anti_fascist", "C", "世界现代史", 9, 9, "第二次世界大战", "World War II", "moe-ls-2022:WD.CON", "知道二战反法西斯性质，了解中国人民与世界人民共同胜利。", '列出二战重要战役', '说明反法西斯同盟意义'),
    T("ls", "历史", "archaeology_evidence", "C", "史料与方法", 7, 8, "考古与历史证据", "Archaeology evidence", "moe-ls-2022:METH", "知道考古发掘提供实物证据，可与文献互证。", '举例考古发现改变认识', '说明层位学基本概念'),
    T("ls", "历史", "historical_timeline_skill", "P", "史料与方法", 7, 7, "绘制历史年表", "Timeline skills", "moe-ls-2022:METH", "能用年表整理朝代或事件顺序，标注起止年代。", '完成中国朝代年表填空', '为近代史事件排序'),
    T("ls", "历史", "map_reading_history", "P", "史料与方法", 7, 8, "历史地图识读", "Historical map reading", "moe-ls-2022:METH", "能在历史地图上读取方位、路线、疆域变化等信息。", '从地图读出行军路线', '比较两张疆域图差异'),
    T("ls", "历史", "primary_secondary_sources", "C", "史料与方法", 7, 7, "一手与二手史料", "Primary and secondary sources", "moe-ls-2022:METH", "能区分文物、当事人记录与后人著作，判断史料价值。", '分类给定史料类型', '说明为什么文物是一手史料'),
    T("ls", "历史", "cause_and_effect", "M", "史料与方法", 8, 8, "历史因果分析", "Cause and effect", "moe-ls-2022:METH", "分析历史事件时能区分原因、经过、结果，避免简单归因。", '用因果链分析辛亥革命', '区分直接原因与根本原因'),
    T("ls", "历史", "compare_historical_figures", "P", "史料与方法", 8, 9, "历史人物比较", "Compare figures", "moe-ls-2022:METH", "能从时代背景评价历史人物，避免绝对化褒贬。", '比较两位改革者异同', '写出评价历史人物角度'),
    T("ls", "历史", "historiography_bias", "M", "史料与方法", 9, 9, "史料的立场与偏见", "Source bias", "moe-ls-2022:METH", "阅读史料时注意作者立场、时代局限，批判性使用材料。", '分析两份材料观点差异', '说明为何要多源互证'),
    T("ls", "历史", "research_mini_project", "P", "史料与方法", 9, 9, "小型史题探究", "Mini history research", "moe-ls-2022:METH", "能围绕明确史题搜集史料、形成观点并口头或书面表达。", '完成一篇短文含史料引用', '汇报探究过程与结论'),
]
