# -*- coding: utf-8 -*-
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from topiclib import T


Pfx = "it"
Sub = "信息科技"

def i(slug, typ, domain, g0, g1, name, en, std, desc, *ev):
    return T(Pfx, Sub, slug, typ, domain, g0, g1, name, en, std, desc, *ev)

IT = [
    i('digital_device_parts', 'C', '信息处理', 1, 2, '认识数字设备部件', 'Digital device parts', ['moe-xxkj-2022:X1.S1.数字设备体验', 'moe-xxkj-2022:PROC'], '能指认计算机、平板的主要部件如屏幕、键盘、主机。', '指出教室电脑的主要部件', '说明输入与输出设备区别'),
    i('mouse_keyboard_use', 'P', '信息处理', 1, 2, '鼠标与键盘操作', 'Mouse and keyboard', ['moe-xxkj-2022:X1.S1.数字设备体验', 'moe-xxkj-2022:PROC'], '能正确使用鼠标点击、拖拽和键盘输入简单文字。', '打开指定程序并关闭', '输入姓名并保存文本'),
    i('share_digital_work', 'P', '信息处理', 1, 2, '分享数字作品', 'Sharing digital work', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '能在教师指导下把绘画、录音等作品展示或传给同学。', '向小组展示一幅数字画', '说明分享前要征得同意'),
    i('photo_video_basics', 'P', '信息处理', 1, 2, '拍照与录像基础', 'Photo and video', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '能使用设备拍摄清晰照片或短视频并简单回看。', '拍摄一张对焦清晰的照片', '录一段十秒介绍视频'),
    i('kind_online_talk', 'C', '信息处理', 1, 2, '文明在线交流', 'Kind online talk', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:NET'], '知道网上说话也要礼貌，不说伤人话，遇到问题告诉大人。', '复述三条网络文明用语', '发现不当言论告诉老师'),
    i('personal_info_privacy', 'C', '信息安全', 1, 2, '个人信息要保密', 'Personal info privacy', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '知道姓名、住址、电话等不能随便告诉陌生人或填在不明网站。', '列举三项不能公开的信息', '遇到索要信息知道拒绝'),
    i('password_basics', 'P', '信息安全', 1, 2, '密码基础', 'Password basics', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '知道账户需要密码保护，不把密码告诉他人或写在明显处。', '设置不易猜的简易密码', '说明为何不能共用密码'),
    i('device_care_rules', 'M', '信息安全', 1, 2, '爱护数字设备', 'Device care', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '了解正确开关机、不随意下载，保护设备和个人信息安全。', '演示正确关机步骤', '说明不点陌生链接的原因'),
    i('ask_adult_for_help', 'M', '信息安全', 1, 2, '遇到问题找大人', 'Ask adults for help', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '在网上遇到奇怪信息或弹窗时，知道暂停操作并求助可信大人。', '角色扮演遇到弹窗求助', '说出两位可求助的大人'),
    i('digital_art_create', 'P', '信息处理', 1, 2, '数字绘画创作', 'Digital art', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '能用简单软件画图形、涂色并保存作品。', '完成一幅主题数字画', '给作品取标题并保存'),
    i('record_voice_message', 'P', '信息处理', 1, 2, '录制语音消息', 'Voice recording', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '能录制清晰语音并回放检查，用于问候或讲故事。', '录一段30秒自我介绍', '调整距离获得清晰录音'),
    i('file_folder_intro', 'C', '信息处理', 1, 2, '文件与文件夹', 'Files and folders', ['moe-xxkj-2022:X1.S1.数字设备体验', 'moe-xxkj-2022:PROC'], '知道文件需要命名和放在文件夹里，便于查找。', '创建文件夹并保存作品', '用有意义的名字命名文件'),
    i('screen_time_balance', 'M', '信息处理', 1, 2, '合理使用屏幕时间', 'Screen time balance', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '知道长时间看屏幕要休息，平衡学习与娱乐。', '制定一天屏幕使用计划', '说出两条保护视力的方法'),
    i('respect_others_work', 'C', '信息处理', 1, 2, '尊重他人数字作品', 'Respect digital work', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:SEC'], '不随意修改或删除他人文件，转载注明来源或征得同意。', '说明为何不能改同学文件', '演示征得同意后再分享'),
    i('safe_software_install', 'C', '信息安全', 1, 2, '安全安装软件', 'Safe software install', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '知道只在可信来源下载应用，安装前请大人检查权限。', '说出两个可信下载渠道', '说明为何不乱装来路不明App'),
    i('emoji_sticker_share', 'P', '信息处理', 1, 2, '表情与贴纸交流', 'Emoji and stickers', ['moe-xxkj-2022:M1.S1.信息交流与分享', 'moe-xxkj-2022:PROC'], '能在合适场合使用表情符号增强表达，避免误解和过度使用。', '选表情匹配三种心情', '说明表情不能代替完整表达'),
    i('online_learning_tools', 'P', '网络', 3, 4, '在线学习工具', 'Online learning tools', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '能使用指定平台观看课程、提交作业并查看反馈。', '登录平台完成一次作业提交', '查看教师评语并改正'),
    i('search_engine_basics', 'P', '网络', 3, 4, '搜索引擎入门', 'Search engines', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '能用关键词搜索学习资料，初步判断结果相关性。', '搜索一个科学问题并选可靠来源', '比较不同关键词搜索结果'),
    i('network_life_services', 'C', '网络', 3, 4, '网络生活服务', 'Online services', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '了解网购、地图、在线预约等常见网络服务及安全注意。', '说出两项网络生活服务', '说明网购需大人陪同'),
    i('email_messaging_intro', 'P', '网络', 3, 4, '邮件与消息入门', 'Email and messaging', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '能在监督下发送格式正确的简短邮件或消息。', '写一封感谢老师的短邮件', '检查收件人和主题是否准确'),
    i('digital_citizenship', 'C', '网络', 3, 4, '数字公民素养', 'Digital citizenship', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:SEC'], '知道网络不是法外之地，尊重版权、不传播谣言。', '列举两条网络行为准则', '识别一条可疑谣言'),
    i('data_is_information', 'C', '数据', 3, 4, '数据就是信息', 'Data as information', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '理解文字、数字、图片等都可成为计算机处理的数据。', '举例五种日常数据', '说明数据与信息的关系'),
    i('collect_sort_data', 'P', '数据', 3, 4, '收集与分类数据', 'Collect and sort data', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能调查班级数据并用表格分类整理。', '统计同学喜欢的运动并制表', '用图表展示分类结果'),
    i('binary_intro', 'C', '数据', 3, 4, '二进制初识', 'Binary intro', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '知道计算机用0和1表示信息，能转换简单十进制与二进制。', '把5和10写成二进制', '解释为何用二进制'),
    i('encoding_text', 'C', '数据', 3, 4, '文字编码', 'Text encoding', ['moe-xxkj-2022:X2.S2.数据编码探秘', 'moe-xxkj-2022:DATA'], '了解ASCII等编码把字符变成数字，乱码与编码有关。', '查编码表找字母对应数字', '解释编码不一致会乱码'),
    i('encoding_images', 'C', '数据', 3, 4, '图像编码初识', 'Image encoding', ['moe-xxkj-2022:X2.S2.数据编码探秘', 'moe-xxkj-2022:DATA'], '知道图像由像素组成，分辨率影响清晰度与文件大小。', '放大图片观察像素', '比较不同分辨率文件大小'),
    i('barcode_qr', 'R', '数据', 3, 4, '条码与二维码', 'Barcodes and QR', ['moe-xxkj-2022:X2.S2.数据编码探秘', 'moe-xxkj-2022:DATA'], '了解条码、二维码如何存储信息并用于生活场景。', '扫描二维码获取文本', '说明为何支付码不能截图给别人'),
    i('strong_passwords', 'P', '信息安全', 3, 4, '强密码与账户安全', 'Strong passwords', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '能设置含字母数字的较强密码并定期更换，了解双重验证概念。', '评估密码强度并改进', '说明双重验证作用'),
    i('phishing_awareness', 'C', '信息安全', 3, 4, '识别网络钓鱼', 'Phishing awareness', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '能识别假冒链接和诈骗邮件的常见特征，不泄露验证码。', '找出钓鱼邮件的可疑点', '说明验证码不能告诉他人'),
    i('privacy_settings', 'P', '信息安全', 3, 4, '隐私设置', 'Privacy settings', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '能在常用应用中设置可见范围，保护个人动态与位置。', '调整一项隐私设置为仅好友可见', '说明公开位置的风险'),
    i('cloud_storage_intro', 'C', '信息处理', 3, 4, '云存储入门', 'Cloud storage', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '了解云盘可备份文件、多设备同步，注意账户安全。', '上传作业到云盘并分享链接', '说明备份防丢失的好处'),
    i('spreadsheet_intro', 'P', '信息处理', 3, 4, '电子表格入门', 'Spreadsheets intro', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能在表格中输入数据、使用简单求和公式。', '制作班级身高统计表', '用公式计算平均值'),
    i('digital_footprint', 'M', '信息安全', 3, 4, '数字足迹', 'Digital footprint', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '知道上网行为会留下记录，发言和上传内容需慎重。', '列举会留下足迹的三项操作', '删除或修改一条不当动态'),
    i('online_collaboration', 'P', '信息处理', 3, 4, '在线协作编辑', 'Online collaboration', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '能与同学共同编辑一份在线文档并查看修改记录。', '小组完成一份在线调查表', '说明版本历史的作用'),
    i('data_visualization', 'R', '数据', 3, 4, '数据可视化', 'Data visualization', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能选择合适的柱形图、饼图展示数据并读图得出结论。', '把统计表转成柱形图', '从图中读出最多最少项'),
    i('information_reliability', 'M', '网络', 3, 4, '信息可靠性判断', 'Information reliability', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '能交叉验证网络信息，优先选择权威来源。', '对比两个来源的同一事件', '说明为何百科需核实'),
    i('data_backup_habit', 'M', '信息处理', 3, 4, '数据备份习惯', 'Data backup habit', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:PROC'], '知道重要作业和照片应备份到云盘或U盘，防止丢失。', '完成一次作业备份', '说明备份频率建议'),
    i('keyboard_shortcuts', 'P', '信息处理', 3, 4, '常用快捷键', 'Keyboard shortcuts', ['moe-xxkj-2022:X1.S1.数字设备体验', 'moe-xxkj-2022:PROC'], '能使用复制粘贴、保存、撤销等快捷键提高效率。', '用快捷键完成复制粘贴', '列出五项常用快捷键'),
    i('algorithm_steps', 'C', '算法', 5, 6, '算法是有序步骤', 'Algorithm as steps', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能把完成任务的过程写成明确、有限的步骤序列。', '写出做三明治的步骤', '检查步骤是否有歧义'),
    i('flowchart_symbols', 'R', '算法', 5, 6, '流程图符号', 'Flowchart symbols', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能使用开始结束、处理、判断等符号绘制流程图。', '为求平均数画流程图', '读懂同伴流程图含义'),
    i('sequential_structure', 'C', '算法', 5, 6, '顺序结构', 'Sequential structure', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '理解算法按顺序逐步执行，前一步结果是后一步输入。', '追踪三步算法输出', '找出顺序错误导致的问题'),
    i('branch_structure', 'C', '算法', 5, 6, '分支结构', 'Branch structure', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能设计含如果…否则…的判断分支解决分类问题。', '为成绩等级画分支图', '编写含判断的伪代码'),
    i('loop_structure', 'C', '算法', 5, 6, '循环结构', 'Loop structure', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能用重复执行处理累加、枚举等问题，避免无限循环。', '用循环求1到100的和', '找出缺少退出条件的循环'),
    i('debug_algorithm', 'M', '算法', 5, 6, '调试算法', 'Debugging algorithms', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '算法结果不对时能逐步追踪、定位并修正错误步骤。', '修复一个排序步骤错误', '记录调试过程'),
    i('open_loop_control', 'C', '算法', 5, 6, '开环控制', 'Open-loop control', ['moe-xxkj-2022:M6.S3.过程与控制', 'moe-xxkj-2022:PROC'], '知道开环控制按预设执行、不检测结果，如定时闹钟。', '举例开环控制设备', '说明开环无法自动纠正偏差'),
    i('closed_loop_control', 'C', '算法', 5, 6, '闭环控制', 'Closed-loop control', ['moe-xxkj-2022:M6.S3.过程与控制', 'moe-xxkj-2022:PROC'], '理解反馈使系统能比较目标与实际并调整，如温控空调。', '画出空调温控闭环图', '比较开环与闭环差异'),
    i('sensor_input', 'C', '信息处理', 5, 6, '传感器采集', 'Sensor input', ['moe-xxkj-2022:M6.S3.过程与控制', 'moe-xxkj-2022:PROC'], '知道光、温、距等传感器把环境量变成数字信号供系统使用。', '读取光线传感器数值', '说明传感器在智能灯中的作用'),
    i('actuator_output', 'C', '信息处理', 5, 6, '执行器输出', 'Actuator output', ['moe-xxkj-2022:M6.S3.过程与控制', 'moe-xxkj-2022:PROC'], '知道电机、蜂鸣器等执行器接收指令产生动作或声音。', '控制小电机正反转', '说明输出与输入对应关系'),
    i('simulate_small_system', 'P', '算法', 5, 6, '模拟小型系统', 'Simulate a system', ['moe-xxkj-2022:X3.S3.小型系统模拟', 'moe-xxkj-2022:ALGO'], '能用软件或硬件模拟交通灯、温室等简单系统运行。', '模拟红绿灯时序', '调整参数观察系统变化'),
    i('block_programming', 'P', '算法', 5, 6, '积木式编程', 'Block programming', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能用图形化编程实现顺序、分支、循环控制角色或设备。', '编写程序让小猫画正方形', '添加碰撞判断分支'),
    i('variable_in_program', 'C', '算法', 5, 6, '程序中的变量', 'Variables', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '知道变量存储会变化的数据，能命名并使用变量计数。', '用变量记录得分', '解释为何循环需要计数变量'),
    i('event_driven', 'C', '算法', 5, 6, '事件驱动', 'Event-driven', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '理解点击、按键等事件触发程序执行相应代码。', '编写点击换造型程序', '说明事件与循环的区别'),
    i('algorithm_efficiency', 'M', '算法', 5, 6, '算法效率', 'Algorithm efficiency', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能比较两种查找方式步骤多少，初步理解效率概念。', '比较顺序找与二分找', '说明为何步骤少更好'),
    i('control_threshold', 'P', '信息处理', 5, 6, '阈值与控制', 'Control thresholds', ['moe-xxkj-2022:M6.S3.过程与控制', 'moe-xxkj-2022:PROC'], '能设置温度或光线阈值触发开关动作，完成简单自动化。', '设置低于20度开加热', '测试阈值改变后的行为'),
    i('system_diagram', 'R', '信息处理', 5, 6, '系统结构图', 'System diagrams', ['moe-xxkj-2022:X3.S3.小型系统模拟', 'moe-xxkj-2022:PROC'], '能绘制输入—处理—输出结构图描述小型信息系统。', '为自动浇花系统画图', '标注各模块功能'),
    i('data_logging', 'P', '数据', 5, 6, '数据记录', 'Data logging', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能连续采集传感器数据并保存，用于后续分析。', '记录一小时温度变化', '从日志找最高最低值'),
    i('network_basics_s3', 'C', '网络', 5, 6, '网络连接基础', 'Network basics', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:NET'], '知道局域网、Wi-Fi、IP地址等基本概念，了解设备如何互联。', '查看本机IP地址', '说明路由器的作用'),
    i('cyberbullying_prevention', 'C', '信息安全', 5, 6, '预防网络欺凌', 'Cyberbullying prevention', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '识别网络欺凌行为，知道保存证据、举报和求助途径。', '列举三种网络欺凌形式', '制定班级网络公约一条'),
    i('ascii_art_encoding', 'R', '数据', 5, 6, '字符画与编码', 'ASCII art', ['moe-xxkj-2022:X2.S2.数据编码探秘', 'moe-xxkj-2022:DATA'], '能用字符排列简单图案，理解字符编码可表达图形文本。', '制作一幅简易字符画', '说明每个字符对应编码'),
    i('internet_architecture', 'C', '网络', 7, 9, '互联网体系结构', 'Internet architecture', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:NET'], '了解分层思想、TCP/IP与域名解析，理解网址访问过程。', '追踪域名解析步骤', '说明HTTP与HTTPS区别'),
    i('web_app_development', 'P', '网络', 7, 9, '网页应用开发', 'Web app development', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:NET'], '能用HTML/CSS/JS制作简单静态页面并实现交互。', '制作个人介绍网页', '添加按钮点击效果'),
    i('api_and_services', 'C', '网络', 7, 9, 'API与网络服务', 'APIs and services', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:NET'], '知道应用通过API获取天气、地图等服务数据。', '调用公开API显示天气', '说明API密钥需保密'),
    i('cloud_computing', 'C', '网络', 7, 9, '云计算', 'Cloud computing', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:NET'], '了解云服务器、弹性扩展等概念及典型应用场景。', '举例三项云服务', '讨论云端存储利弊'),
    i('network_security', 'C', '信息安全', 7, 9, '网络安全', 'Network security', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:SEC'], '了解防火墙、加密传输等机制，养成安全上网习惯。', '识别HTTPS安全标识', '说明公共Wi-Fi风险'),
    i('iot_sensors_actuators', 'P', '网络', 7, 9, '物联网传感与执行', 'IoT sensors', ['moe-xxkj-2022:M8.S4.物联网实践与探索', 'moe-xxkj-2022:NET'], '能搭建含传感器和执行器的物联网小项目并远程查看数据。', '完成温湿度上报项目', '设置超阈值报警'),
    i('iot_protocols', 'C', '网络', 7, 9, '物联网通信', 'IoT protocols', ['moe-xxkj-2022:M8.S4.物联网实践与探索', 'moe-xxkj-2022:NET'], '了解MQTT等轻量协议适合设备互联，理解发布订阅模式。', '描述智能家居消息流', '比较物联网与互联网差异'),
    i('edge_computing', 'C', '网络', 7, 9, '边缘计算初识', 'Edge computing', ['moe-xxkj-2022:M8.S4.物联网实践与探索', 'moe-xxkj-2022:NET'], '知道在设备端预处理数据可减少延迟和带宽占用。', '举例边缘计算场景', '说明本地处理隐私优势'),
    i('big_data_intro', 'C', '数据', 7, 9, '大数据初识', 'Big data intro', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '了解Volume、Velocity、Variety特征及大数据典型应用。', '举例大数据应用', '讨论数据过多带来的问题'),
    i('database_basics', 'P', '数据', 7, 9, '数据库基础', 'Database basics', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能用表格数据库进行增删查改，理解主键与字段类型。', '建立学生信息表并查询', '设计合理字段类型'),
    i('data_cleaning', 'P', '数据', 7, 9, '数据清洗', 'Data cleaning', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '能发现缺失、重复、异常值并进行基本清洗。', '清理一份含空值的数据', '说明清洗对分析的重要性'),
    i('machine_learning_intro', 'C', '人工智能', 7, 9, '机器学习入门', 'Machine learning intro', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '了解监督学习用标注数据训练模型，能完成简单分类实验。', '训练图像分类小模型', '说明训练集与测试集'),
    i('ai_perception', 'C', '人工智能', 7, 9, '人工智能感知', 'AI perception', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '知道视觉、语音识别依赖特征提取与模型推理。', '体验语音转文字', '讨论识别错误原因'),
    i('neural_network_concept', 'C', '人工智能', 7, 9, '神经网络概念', 'Neural networks', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '了解神经元、层、权重等基本概念，不要求手工推导。', '画出简单神经网络示意', '说明深度学习需大量数据'),
    i('ai_ethics_bias', 'M', '人工智能', 7, 9, '人工智能伦理', 'AI ethics', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '讨论算法偏见、就业影响、深度伪造等伦理与社会问题。', '分析一个偏见案例', '提出一条负责任AI原则'),
    i('smart_society_cases', 'C', '人工智能', 7, 9, '智慧社会应用', 'Smart society', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '了解智慧交通、医疗、城市治理等应用及数据支撑。', '举例本地智慧应用', '讨论数据隐私平衡'),
    i('connected_smart_design', 'P', '人工智能', 7, 9, '互联智能设计', 'Connected smart design', ['moe-xxkj-2022:X4.S4.互联智能设计', 'moe-xxkj-2022:AI'], '能设计含感知、联网、智能决策的小型互联系统方案。', '提交智能校园方案', '答辩说明模块协作'),
    i('algorithm_advanced', 'C', '算法', 7, 9, '常用算法思想', 'Algorithm patterns', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '了解分治、贪心、动态规划等思想及适用场景入门。', '用分治思想找最大数', '比较两种算法时间复杂度'),
    i('sorting_searching', 'P', '算法', 7, 9, '排序与查找', 'Sorting and searching', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能实现冒泡或二分查找，理解有序数据提高查找效率。', '实现二分查找函数', '比较顺序与二分步骤数'),
    i('recursion_intro', 'C', '算法', 7, 9, '递归初识', 'Recursion intro', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '理解函数调用自身解决规模更小同类问题，注意终止条件。', '用递归算阶乘', '找出缺少基例的递归'),
    i('text_programming', 'P', '算法', 7, 9, '文本语言编程', 'Text programming', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能用Python等文本语言编写含函数、列表的程序。', '编写统计列表平均程序', '使用函数封装重复代码'),
    i('encryption_basics', 'C', '信息安全', 7, 9, '加密基础', 'Encryption basics', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '了解对称与非对称加密作用，知道HTTPS保护传输。', '体验凯撒密码加密', '说明公钥私钥用途入门'),
    i('digital_identity', 'C', '信息安全', 7, 9, '数字身份认证', 'Digital identity', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '了解实名认证、OAuth登录等机制及个人信息保护要求。', '比较不同登录方式安全性', '说明最小必要授权'),
    i('open_source_license', 'C', '信息处理', 7, 9, '开源与许可', 'Open source licenses', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:NET'], '知道开源软件可学习修改，但需遵守许可协议。', '查找一个项目的开源协议', '说明署名与商用限制'),
    i('tech_innovation_project', 'P', '信息处理', 7, 9, '科技创新项目', 'Innovation project', ['moe-xxkj-2022:X4.S4.互联智能设计', 'moe-xxkj-2022:AI'], '能组队完成从需求到原型的信息科技创新小项目并展示。', '提交项目文档与演示', '回答评委技术问题'),
    i('data_privacy_law', 'C', '信息安全', 7, 9, '数据与隐私法规', 'Data privacy law', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '了解个人信息保护法对收集使用数据的基本要求。', '列举两项法定用户权利', '说明App过度索权问题'),
    i('ai_generated_content', 'M', '人工智能', 7, 9, 'AIGC与辨别', 'AIGC awareness', ['moe-xxkj-2022:M9.S4.人工智能与智慧社会', 'moe-xxkj-2022:AI'], '能识别AI生成文本图像的可能特征，注明AI辅助创作。', '判断一段文字是否AI生成', '说明标注AI内容的意义'),
    i('blockchain_concept', 'C', '数据', 7, 9, '区块链概念', 'Blockchain concept', ['moe-xxkj-2022:M4.S2.数据与编码', 'moe-xxkj-2022:DATA'], '了解区块链去中心化、不可篡改特点及有限应用场景。', '说明区块链不等于比特币全部', '讨论溯源应用价值'),
    i('program_debugging_advanced', 'M', '算法', 7, 9, '高级调试', 'Advanced debugging', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '会使用断点、日志、单元测试定位复杂程序错误。', '修复一个含逻辑错误程序', '编写两个单元测试'),
    i('human_computer_interaction', 'C', '信息处理', 7, 9, '人机交互', 'HCI basics', ['moe-xxkj-2022:X4.S4.互联智能设计', 'moe-xxkj-2022:PROC'], '了解可用性、无障碍设计原则，能评价界面优劣。', '评估一个App界面', '提出一条无障碍改进'),
    i('information_system_lifecycle', 'C', '信息处理', 7, 9, '信息系统生命周期', 'IS lifecycle', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:PROC'], '了解需求分析、设计、实现、运维、退役等阶段及迭代思想。', '为校园系统画生命周期', '说明运维监控重要性'),
    i('computational_thinking', 'M', '算法', 7, 9, '计算思维综合', 'Computational thinking', ['moe-xxkj-2022:M5.S3.身边的算法', 'moe-xxkj-2022:ALGO'], '能把复杂问题分解、抽象、模式识别并设计算法实现。', '分解一个配送路径问题', '说明抽象忽略细节'),
    i('version_control_intro', 'C', '信息处理', 7, 9, '版本控制入门', 'Version control', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:PROC'], '了解Git等工具记录代码变更，便于协作与回退。', '解释提交与回滚概念', '说明分支用于并行开发'),
    i('agile_scrum_basics', 'C', '信息处理', 7, 9, '敏捷开发初识', 'Agile basics', ['moe-xxkj-2022:M7.S4.互联网应用与创新', 'moe-xxkj-2022:PROC'], '了解迭代、用户故事、站会等敏捷方法提高团队协作。', '写一个用户故事', '说明迭代比一次交付灵活'),
    i('social_engineering', 'C', '信息安全', 7, 9, '社会工程学防范', 'Social engineering', ['moe-xxkj-2022:M2.S1.信息隐私与安全', 'moe-xxkj-2022:SEC'], '识别冒充熟人、客服等骗取信息的手段，不轻信转账要求。', '分析一个诈骗话术', '说明核实身份的方法'),
    i('digital_wellbeing', 'M', '信息处理', 7, 9, '数字健康', 'Digital wellbeing', ['moe-xxkj-2022:M3.S2.在线学习与生活', 'moe-xxkj-2022:PROC'], '管理屏幕时间、通知干扰，保持线上线下生活平衡。', '统计一周屏幕使用', '制定减少干扰的设置'),
]

if __name__ == "__main__":
    from topiclib import dump
    dump("it.json", IT)
