# -*- coding: utf-8 -*-
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from topiclib import T

Pfx, Sub = "dl", "地理"
def t(slug, typ, domain, g0, g1, name, en, std, desc, *ev):
    return T(Pfx, Sub, slug, typ, domain, g0, g1, name, en, std, desc, *ev)

HS_GEOGRAPHY = [
    # 自然地理 G1 · 年级10
    t("earth_motion_geo_meaning", "P", "自然地理", 10, 10, "地球运动地理意义", "Geographic meaning of Earth motion",
      "moe-dl-2017:G1",
      "能用黄赤交角、太阳直射点移动解释昼夜长短、正午太阳高度和四季，建立可计算的空间模型而非只记现象。",
      "计算某纬度二分二至的正午太阳高度", "用日照图判断晨昏线与日期"),
    t("atmosphere_heating_motion", "R", "自然地理", 10, 10, "大气受热与运动", "Atmospheric heating and motion",
      "moe-dl-2017:G1",
      "能用太阳辐射、地面辐射、大气逆辐射解释保温过程，分析热力环流的形成条件与常见表现。",
      "画出白天与夜晚大气受热过程图", "用热力环流解释海陆风或城市热岛"),
    t("pressure_belts_wind_belts", "R", "自然地理", 10, 10, "气压带风带", "Pressure belts and wind belts",
      "moe-dl-2017:G1",
      "能用三圈环流模型推导气压带风带分布及其季节移动，解释气候带与信风、西风的关系。",
      "在空白图上标注气压带风带", "用移动原理解释地中海气候夏季干燥"),
    t("weather_systems_analysis", "P", "自然地理", 10, 10, "天气系统", "Weather systems",
      "moe-dl-2017:G1",
      "能判读锋面、气旋、反气旋天气图，预报阴雨或晴朗并说明气团属性与过境序列。",
      "根据等压线图判断锋面气旋位置", "解释冷锋过境前后的天气序列"),
    t("water_cycle_ocean_currents", "R", "自然地理", 10, 10, "水循环与洋流", "Water cycle and ocean currents",
      "moe-dl-2017:G1",
      "能用水量平衡和洋流成因模式分析海陆间循环与热量输送，评价洋流对气候与渔场的影响。",
      "画出含洋流的大洋环流简图", "解释秘鲁渔场或西欧温和气候的洋流因素"),
    t("landform_shaping_processes", "C", "自然地理", 10, 10, "地表形态塑造", "Landform-shaping processes",
      "moe-dl-2017:G1",
      "能区分内力与外力，分析褶皱断层与流水、风力、冰川地貌的过程—形态对应关系。",
      "根据景观图推断主导营力", "比较峡谷与冲积扇的形成条件"),
    t("vegetation_soil_coupling", "C", "自然地理", 10, 10, "植被与土壤", "Vegetation and soils",
      "moe-dl-2017:G1",
      "能把气候—植被—土壤作为耦合系统，分析地带性规律与地方性因素造成的偏离。",
      "匹配气候类型与典型植被土壤", "解释同一山地垂直带谱出现差异的原因"),
    t("physical_env_integrity", "C", "自然地理", 10, 10, "自然地理环境整体性", "Integrity of the physical environment",
      "moe-dl-2017:G1",
      "能用要素相互作用说明牵一发而动全身，分析一个要素变化如何通过反馈改变整个环境。",
      "用森林破坏一例画出要素反馈链", "评价只治理单一要素方案的漏洞"),
    t("physical_env_differentiation", "C", "自然地理", 10, 10, "自然地理环境差异性", "Differentiation of the physical environment",
      "moe-dl-2017:G1",
      "能用纬度地带性、干湿度地带性、垂直地带性解释景观分异，并识别地方性因素的干扰。",
      "解释两地同纬度景观差异的主导因素", "在剖面图上标出垂直带谱"),
    t("natural_hazard_causes", "C", "自然地理", 10, 10, "自然灾害成因", "Causes of natural hazards",
      "moe-dl-2017:G1",
      "能从孕灾环境、致灾因子、承灾体分析灾害风险，比较地震、洪水、台风的空间格局。",
      "用风险思路评估一地某类灾害", "提出基于成因的减灾措施而非口号"),

    # 人文地理 G2 · 年级11
    t("population_distribution_migration", "C", "人文地理", 11, 11, "人口分布与迁移", "Population distribution and migration",
      "moe-dl-2017:G2",
      "能用推拉模型和环境承载力分析人口分布与迁移，解读人口金字塔与政策效应。",
      "根据金字塔判断增长阶段", "用推拉因素解释一次国内或国际迁移"),
    t("urbanization_process", "C", "人文地理", 11, 11, "城镇化过程", "Urbanization process",
      "moe-dl-2017:G2",
      "能分析城镇化水平、速度与问题，比较郊区化、逆城镇化与中国城镇化的阶段特征。",
      "用城镇化曲线解释某国所处阶段", "评价摊大饼扩张的资源环境代价"),
    t("agricultural_location", "P", "人文地理", 11, 11, "农业区位", "Agricultural location",
      "moe-dl-2017:G2",
      "能用杜能模型与交通、技术、政策、市场等现代因素分析农业类型布局及其动态变化。",
      "用杜能圈解释城郊农业", "分析一作物区位变化的主导因素替换"),
    t("industrial_location", "P", "人文地理", 11, 11, "工业区位", "Industrial location",
      "moe-dl-2017:G2",
      "能比较原料指向、市场指向、动力指向与产业集聚，分析工业区位选择如何随成本结构变化。",
      "为给定工厂选择区位并陈述权衡", "解释产业转移中区位因素的改变"),
    t("services_and_transport", "C", "人文地理", 11, 11, "服务业与交通", "Services and transport",
      "moe-dl-2017:G2",
      "能用中心地理论与交通可达性分析服务业等级体系和交通对区域联系的塑造。",
      "用中心地原理解释城市商业网点", "评价一条交通线对腹地的重组作用"),
    t("regional_culture_landscape", "L", "人文地理", 11, 11, "地域文化", "Regional culture",
      "moe-dl-2017:G2",
      "能从民居、饮食、信仰、语言等景观符号解读地域文化与自然环境、历史过程的关系，避免把文化本质化。",
      "用民居结构说明气候适应", "比较两地文化景观的形成机制"),
    t("man_land_relationship_ideas", "M", "人文地理", 11, 11, "人地关系思想", "Human-environment thought",
      "moe-dl-2017:G2",
      "能比较环境决定论、可能论、适应论与可持续发展思想，用思想史眼光评价当代开发方案。",
      "指出一段论述所属人地观", "用案例批判绝对的环境决定论"),
    t("sustainable_development_geo", "M", "人文地理", 11, 11, "可持续发展", "Sustainable development",
      "moe-dl-2017:G2",
      "能用经济、社会、环境三个支柱评估区域路径，提出可监测指标，并检讨先污染后治理叙事的适用边界。",
      "为某区域设计三项可监测指标", "评价先污染后治理说法的适用边界"),

    # 自然地理基础 S1 · 年级12
    t("lithosphere_material_cycle", "R", "自然地理基础", 12, 12, "岩石圈物质循环", "Lithosphere material cycle",
      "moe-dl-2017:S1",
      "能用岩浆岩、沉积岩、变质岩转化模型解释岩石圈物质循环，把构造过程与岩石记录对应起来。",
      "画出三大类岩石转化示意图", "根据岩石特征推断形成环境"),
    t("climate_causes_synthesis", "P", "自然地理基础", 12, 12, "气候成因综合", "Synthesizing climate causes",
      "moe-dl-2017:S1",
      "能综合太阳辐射、大气环流、下垫面、洋流、人类活动解释气候类型，完成多因素合成分析。",
      "对一气候类型写出主导与次要成因", "解释同纬度东西岸气候差异"),
    t("hydrology_feature_analysis", "P", "自然地理基础", 12, 12, "水文特征分析", "Hydrological feature analysis",
      "moe-dl-2017:S1",
      "能从补给类型、径流变化、含沙量、结冰期等分析河流水文，比较不同气候区的河流过程。",
      "根据流量过程线推断补给类型", "解释黄河下游地上河的水文地貌耦合"),
    t("geo_info_tech_application", "P", "自然地理基础", 12, 12, "地理信息技术应用", "Geographic information technology",
      "moe-dl-2017:S1",
      "能说明遥感、地理信息系统、卫星导航在资源调查与灾害监测中的分工，完成简单空间叠加分析思路。",
      "为洪涝监测选择合适遥感时相", "设计一个图层叠加解决实际问题"),

    # 区域发展 S2 · 年级12
    t("regional_development_conditions", "C", "区域发展", 12, 12, "区域发展条件", "Regional development conditions",
      "moe-dl-2017:S2",
      "能从区位、资源、交通、政策综合评价区域发展条件，区分优势、限制性因素与可变条件。",
      "完成一份区域条件评估表", "指出一项曾经的优势如何转化为约束"),
    t("resource_exhausted_city_transition", "C", "区域发展", 12, 12, "资源枯竭型城市转型", "Resource-exhausted city transition",
      "moe-dl-2017:S2",
      "能分析矿业城市生命周期与路径依赖，比较产业替代、生态修复与人口策略。",
      "用就业与产业结构数据诊断转型阶段", "评价再造一个同类矿城的方案"),
    t("industrial_relocation", "C", "区域发展", 12, 12, "产业转移", "Industrial relocation",
      "moe-dl-2017:S2",
      "能用劳动力、土地、环境成本与市场准入解释产业转移，分析转入区与转出区的损益及环境风险。",
      "画一次产业转移的动力与阻力图", "评价污染伴随转移的风险"),
    t("interregional_linkages", "C", "区域发展", 12, 12, "区际联系", "Interregional linkages",
      "moe-dl-2017:S2",
      "能用流域、交通廊道、城市群分析区际分工与合作冲突，解释虹吸与扩散效应。",
      "用物流或通勤数据说明区际联系强度", "分析行政区经济如何阻碍一体化"),
    t("belt_road_geo_perspective", "C", "区域发展", 12, 12, "一带一路地理视角", "Belt and Road geographic view",
      "moe-dl-2017:S2",
      "能从通道、节点、资源环境约束分析共建一带一路的地理逻辑，比较陆海通道的风险。",
      "在地图上分析一条经济走廊的自然障碍", "评价港口或铁路节点的腹地条件"),

    # 资源环境与国家安全 S3 · 年级12
    t("cultivated_land_security", "C", "资源环境与国家安全", 12, 12, "耕地资源安全", "Cultivated land security",
      "moe-dl-2017:S3",
      "能从数量、质量、生态分析耕地安全，评估占用、退化与占补平衡政策的空间后果。",
      "用人均耕地与质量等级数据提出风险判断", "评价城市扩张对优质耕地的挤占"),
    t("water_resource_security", "C", "资源环境与国家安全", 12, 12, "水资源安全", "Water resource security",
      "moe-dl-2017:S3",
      "能分析时空不匹配、水质与跨境水资源风险，比较调水、节水、非常规水源的适用条件。",
      "计算简单水资源供需缺口", "评价跨流域调水的生态与社会代价"),
    t("energy_security_geo", "C", "资源环境与国家安全", 12, 12, "能源安全", "Energy security",
      "moe-dl-2017:S3",
      "能从生产、运输、储备与转型分析能源安全，比较化石能源通道风险与可再生能源空间格局。",
      "在地图上标出主要能源进口通道风险点", "评价电动化对电力与矿产的新依赖"),
    t("environmental_security", "C", "资源环境与国家安全", 12, 12, "环境安全", "Environmental security",
      "moe-dl-2017:S3",
      "能把污染、生态退化、跨境环境问题纳入安全框架，分析环境风险如何转化为社会与政治风险。",
      "用污染物迁移说明跨界风险", "提出基于源头的环境安全措施"),
    t("maritime_territory_security", "R", "资源环境与国家安全", 12, 12, "海洋国土与安全", "Maritime territory and security",
      "moe-dl-2017:S3",
      "能区分内水、领海、毗连区、专属经济区的权利差异，分析海洋资源、通道与岛礁的安全意义。",
      "在示意图上标出不同海域权利", "评价某一海洋开发活动的法理与地理条件"),
]
