# -*- coding: utf-8 -*-
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from topiclib import T


Pfx = "english"
Sub = "英语"

def e(slug, typ, domain, g0, g1, name, en, std, desc, *ev):
    return T(Pfx, Sub, slug, typ, domain, g0, g1, name, en, std, desc, *ev)

ENGLISH = [
    e('alphabet_recognition', 'L', '语音词汇语法', 3, 4, '英文字母认读', 'Alphabet recognition', 'moe-yy-2022:LK.L1.语音', '能按顺序认读26个英文字母，区分大小写并正确书写。', '指读字母表中的任意字母', '抄写大小写字母各一行'),
    e('phonics_short_vowels', 'P', '语音词汇语法', 3, 4, '短元音拼读', 'Short vowel phonics', 'moe-yy-2022:LK.L1.语音', '能在CVC单词中听辨并拼读a、e、i、o、u的短元音。', '拼读cat、bed、big等词', '听音选出发短元音的单词'),
    e('consonant_blends', 'P', '语音词汇语法', 3, 4, '辅音连缀', 'Consonant blends', 'moe-yy-2022:LK.L1.语音', '能拼读含bl、st、tr等辅音连缀的简单单词。', '拼读black、stop、tree', '在词表中找出含辅音连缀的词'),
    e('classroom_vocabulary', 'L', '语音词汇语法', 3, 4, '课堂常用词汇', 'Classroom vocabulary', 'moe-yy-2022:LK.L1.词汇', '能听懂并说出desk、book、pencil等课堂物品名称。', '指认教室里的常见物品', '听指令拿出指定文具'),
    e('family_words', 'L', '语音词汇语法', 3, 4, '家庭成员词汇', 'Family words', 'moe-yy-2022:LK.L1.词汇', '能说出father、mother、sister等家庭成员英文词并简单介绍。', '用This is my…介绍家人', '看图说出对应家庭成员'),
    e('be_verb_present', 'C', '语音词汇语法', 3, 4, 'be动词现在时', 'Present tense of be', 'moe-yy-2022:LK.L1.语法', '能用I am/You are/He is描述自己和他人的基本状态。', '用be动词造三个简单句', '改正He are happy中的错误'),
    e('plural_nouns_s', 'C', '语音词汇语法', 3, 4, '名词复数加s', 'Plural nouns with -s', 'moe-yy-2022:LK.L1.语法', '知道多数可数名词复数加s，能在口语和书写中使用。', '把book变成复数并朗读', '看图说There are three cats'),
    e('greetings_introduction', 'P', '听与说', 3, 4, '问候与自我介绍', 'Greetings and introduction', 'moe-yy-2022:LS.L1', '能听懂并运用Hello、Good morning及My name is…做简短自我介绍。', '与同伴互相问候并介绍姓名', '向新同学做一分钟自我介绍'),
    e('classroom_commands', 'P', '听与说', 3, 4, '听懂课堂指令', 'Classroom commands', 'moe-yy-2022:LS.L1', '能听懂Stand up、Open your book等常见课堂指令并做出反应。', '听到指令后正确起立或坐下', '根据口头指令完成取物动作'),
    e('ask_answer_name', 'P', '听与说', 3, 4, '询问与回答姓名', 'Asking names', 'moe-yy-2022:LS.L1', '能问What is your name?并用My name is…或I am…回答。', '向三位同学询问姓名并记录', '角色扮演中正确问答姓名'),
    e('describe_colors', 'P', '听与说', 3, 4, '描述颜色', 'Describing colors', 'moe-yy-2022:LS.L1', '能用It is red/blue…描述物品颜色，并询问What color is it?', '说出身边五件物品的颜色', '回答What color is the apple?'),
    e('simple_qa_dialogue', 'P', '听与说', 3, 4, '简单问答对话', 'Simple Q&A dialogue', 'moe-yy-2022:LS.L1', '能就年龄、喜好等简单问题与同伴进行两三轮问答。', 'How old are you?问答流畅', '就Do you like…?表达喜好'),
    e('read_aloud_words', 'P', '读与看', 3, 4, '朗读单词', 'Reading words aloud', 'moe-yy-2022:RV.L1', '能看着单词表或课文准确朗读学过的词汇。', '流利朗读一页单词表', '纠正同伴读错的单词'),
    e('picture_sentence_reading', 'R', '读与看', 3, 4, '看图读短句', 'Picture sentence reading', 'moe-yy-2022:RV.L1', '能借助图片读懂This is a…等一到两句英文。', '看图读出对应英文句子', '选出与图片匹配的句子'),
    e('sight_words', 'L', '读与看', 3, 4, '高频词认读', 'Sight word reading', 'moe-yy-2022:RV.L1', '能认读the、and、is等高频词并在短句中理解其意义。', '快速认读一组高频词卡片', '在短句中指出the和and'),
    e('read_labels_signs', 'R', '读与看', 3, 4, '读标签与标识', 'Reading labels', 'moe-yy-2022:RV.L1', '能读懂课本和教室中简单的英文标签与标识。', '读出图书角英文标签', '解释EXIT标识的含义'),
    e('follow_written_steps', 'P', '读与看', 3, 4, '看懂简单步骤', 'Following written steps', 'moe-yy-2022:RV.L1', '能按一到两步英文书面指令完成涂色或连线等活动。', '按Color the apple red完成涂色', '按Draw a line连接配对项'),
    e('copy_words_sentences', 'P', '写', 3, 4, '抄写单词与句子', 'Copying words', 'moe-yy-2022:WR.L1', '能工整抄写单词和简单句，注意字母占格与间距。', '抄写五个单词无漏字母', '抄写一句Hello, I am Tom.'),
    e('write_own_name', 'P', '写', 3, 4, '书写英文姓名', 'Writing your name', 'moe-yy-2022:WR.L1', '能正确书写自己的英文名或拼音名，首字母大写。', '独立写出英文姓名', '检查同学姓名首字母是否大写'),
    e('fill_word_blanks', 'P', '写', 3, 4, '选词填空', 'Word gap fill', 'moe-yy-2022:WR.L1', '能在句子空格处填入合适的单词完成意义。', '从词库选词完成I am a ___', '检查填空后句子是否通顺'),
    e('write_simple_sentences', 'P', '写', 3, 4, '写简单句', 'Simple sentences', 'moe-yy-2022:WR.L1', '能写出This is my bag.等主谓结构完整的简单句。', '写两句描述自己的物品', '检查句子首字母和句号'),
    e('capital_punctuation', 'R', '写', 3, 4, '句首大写与标点', 'Capitals and punctuation', 'moe-yy-2022:WR.L1', '知道英文句首大写、句末用句号，能在书写中基本做到。', '改正句首未大写的句子', '给缺少句号的句子补上标点'),
    e('english_names_culture', 'C', '文化与语用', 3, 4, '英文名与称呼', 'English names', 'moe-yy-2022:CU.L1', '了解英语国家常见名字和Mr/Miss等称呼，能礼貌称呼他人。', '说出三个常见英文名', '用Mr/Miss称呼老师'),
    e('classroom_politeness', 'C', '文化与语用', 3, 4, '课堂礼貌用语', 'Classroom politeness', 'moe-yy-2022:CU.L1', '能使用Please、Thank you、Sorry等礼貌用语参与课堂交流。', '请求借用物品时使用Please', '收到帮助时说Thank you'),
    e('festival_spring_festival', 'C', '文化与语用', 3, 4, '春节英语表达', 'Spring Festival in English', 'moe-yy-2022:CU.L1', '能用简单英语介绍春节及红包、团圆等文化元素。', '用两句英语介绍春节', '说出Happy New Year的使用场合'),
    e('food_culture_words', 'C', '文化与语用', 3, 4, '中西饮食词汇', 'Food culture words', 'moe-yy-2022:CU.L1', '能说出rice、dumpling、hamburger等词并了解部分中西饮食差异。', '区分中式和西式食物名称', '用I like…表达饮食偏好'),
    e('listen_and_repeat', 'M', '学习策略', 3, 4, '听音跟读', 'Listen and repeat', 'moe-yy-2022:ST.L1', '能模仿录音或教师发音跟读单词和短句，注意语调。', '跟读课文录音三遍', '对比自己的读音与示范'),
    e('use_pictures_guess', 'M', '学习策略', 3, 4, '借助图片理解', 'Using pictures', 'moe-yy-2022:ST.L1', '遇到生词时能借助插图或情境猜测大意。', '看图猜出新单词意思', '说明图片如何帮助理解'),
    e('word_card_review', 'M', '学习策略', 3, 4, '单词卡复习', 'Word card review', 'moe-yy-2022:ST.L1', '会用单词卡自主复习，能认读卡面英文并说中文义。', '用单词卡自测十个词', '把易错词单独标记复习'),
    e('partner_practice', 'M', '学习策略', 3, 4, '同伴结对练习', 'Partner practice', 'moe-yy-2022:ST.L1', '能与同伴结对练对话、互查朗读，主动纠正发音。', '与同伴完成一组对话练习', '互相检查抄写作业'),
    e('phonics_long_vowels', 'P', '语音词汇语法', 5, 6, '长元音拼读', 'Long vowel phonics', 'moe-yy-2022:LK.L2.语音', '能拼读含长元音字母组合的单词，如cake、bike、home。', '拼读含magic e的单词', '区分短音cat与长音cake'),
    e('word_families', 'C', '语音词汇语法', 5, 6, '词族与词缀', 'Word families', 'moe-yy-2022:LK.L2.词汇', '能通过词根或常见后缀理解play-player等词族关系。', '说出play和player的联系', '用-unhappy推测词义'),
    e('present_simple_habits', 'C', '语音词汇语法', 5, 6, '一般现在时', 'Present simple', 'moe-yy-2022:LK.L2.语法', '能用一般现在时描述日常习惯和事实，注意第三人称单数。', '用He plays…描述他人习惯', '改正She go to school'),
    e('past_simple_regular', 'C', '语音词汇语法', 5, 6, '一般过去时规则变化', 'Regular past tense', 'moe-yy-2022:LK.L2.语法', '能在规则动词后加-ed表达过去发生的动作。', '用visited描述昨天活动', '写出三个规则动词过去式'),
    e('comparative_adjectives', 'C', '语音词汇语法', 5, 6, '形容词比较级', 'Comparatives', 'moe-yy-2022:LK.L2.语法', '能用bigger、taller等比较级比较两个事物。', '比较两个水果的大小', '用than连接比较句'),
    e('superlative_adjectives', 'C', '语音词汇语法', 5, 6, '形容词最高级', 'Superlatives', 'moe-yy-2022:LK.L2.语法', '能用biggest、most interesting等最高级在范围内比较多个事物。', '在三人中说出谁最高', '写出interesting的最高级'),
    e('prepositions_place', 'C', '语音词汇语法', 5, 6, '方位介词', 'Prepositions of place', 'moe-yy-2022:LK.L2.语法', '能用in、on、under、behind等描述物品位置。', '描述书在课桌里还是上', '根据介词摆放物品'),
    e('daily_routine_talk', 'P', '听与说', 5, 6, '谈论日常作息', 'Daily routine talk', 'moe-yy-2022:LS.L2', '能口头描述一天的主要活动，使用一般现在时。', '介绍自己早上起床到睡觉', '回答When do you…?'),
    e('ask_give_directions', 'P', '听与说', 5, 6, '问路与指路', 'Asking directions', 'moe-yy-2022:LS.L2', '能听懂并说出Go straight、Turn left等简单指路表达。', '角色扮演问去图书馆的路', '根据地图口头指路'),
    e('describe_appearance', 'P', '听与说', 5, 6, '描述外貌', 'Describing appearance', 'moe-yy-2022:LS.L2', '能用He is tall/She has long hair等描述人物外貌。', '描述一位同学的外貌', '听描述找出对应人物'),
    e('retell_short_story', 'P', '听与说', 5, 6, '复述短故事', 'Retelling stories', 'moe-yy-2022:LS.L2', '能根据图片或关键词复述三到五句的短故事大意。', '看图复述故事开头和结尾', '使用first、then连接'),
    e('group_discussion', 'P', '听与说', 5, 6, '小组讨论', 'Group discussion', 'moe-yy-2022:LS.L2', '能在小组中就熟悉话题发表意见并回应他人。', '在讨论中至少发言两次', '用I agree/I think回应'),
    e('read_short_paragraph', 'P', '读与看', 5, 6, '阅读短段落', 'Reading paragraphs', 'moe-yy-2022:RV.L2', '能朗读并理解五到八句的连贯段落。', '朗读一段关于爱好的短文', '回答段落中的细节问题'),
    e('skimming_main_idea', 'M', '读与看', 5, 6, '略读抓主旨', 'Skimming for main idea', 'moe-yy-2022:RV.L2', '能快速浏览短文并说出段落主要讲什么。', '限时30秒说出短文主题', '排除与主旨无关的选项'),
    e('dictionary_lookup', 'P', '读与看', 5, 6, '查英语词典', 'Using a dictionary', 'moe-yy-2022:RV.L2', '能按字母顺序在词典中查找单词并读懂简单释义。', '查三个生词的音标和释义', '说明词条中词性标记'),
    e('read_dialogue_text', 'R', '读与看', 5, 6, '阅读对话文本', 'Reading dialogues', 'moe-yy-2022:RV.L2', '能读懂购物、问路等情境对话并把握说话者意图。', '读出对话并分角色', '回答对话发生的地点'),
    e('read_infographic', 'R', '读与看', 5, 6, '读图表信息', 'Reading infographics', 'moe-yy-2022:RV.L2', '能从简单图表或信息图中读取数字和标签信息。', '从柱状图读出最多的一项', '用英语说出图表标题'),
    e('write_paragraph_hobby', 'P', '写', 5, 6, '写爱好段落', 'Writing about hobbies', 'moe-yy-2022:WR.L2', '能写四到六句介绍自己爱好的小段落。', '写出含主题句的爱好段', '使用because说明原因'),
    e('write_postcard', 'P', '写', 5, 6, '写明信片', 'Writing a postcard', 'moe-yy-2022:WR.L2', '能按明信片格式写简短问候和行程描述。', '完成一张旅游明信片', '包含称呼和落款'),
    e('write_diary_entry', 'P', '写', 5, 6, '写英语日记', 'Diary writing', 'moe-yy-2022:WR.L2', '能用过去时写三到五句记录一天中有趣的事。', '用Yesterday I…开头写日记', '检查过去式拼写'),
    e('letter_format_basic', 'R', '写', 5, 6, '书信基本格式', 'Letter format', 'moe-yy-2022:WR.L2', '了解英文书信称呼、正文和结尾的基本格式。', '按格式写一封邀请信', '标出信件的三个部分'),
    e('edit_spelling_grammar', 'M', '写', 5, 6, '修改拼写与语法', 'Editing writing', 'moe-yy-2022:WR.L2', '能发现同伴习作中的明显拼写和语法错误并改正。', '找出一段文字中的三处错误', '说明每处修改理由'),
    e('western_festivals', 'C', '文化与语用', 5, 6, '西方节日', 'Western festivals', 'moe-yy-2022:CU.L2', '了解Christmas、Halloween等节日及常见英语表达。', '说出两个西方节日及活动', '比较中西节日习俗'),
    e('sports_culture', 'C', '文化与语用', 5, 6, '运动文化', 'Sports culture', 'moe-yy-2022:CU.L2', '能谈论足球、篮球等运动并用英语表达观赛和参与体验。', '用英语介绍一项喜欢的运动', '了解一项运动的起源国家'),
    e('travel_english', 'C', '文化与语用', 5, 6, '旅行英语', 'Travel English', 'moe-yy-2022:CU.L2', '能使用机场、酒店等场景中的常见英语表达。', '模拟办理登机手续对话', '说出三件旅行必备物品英文'),
    e('email_etiquette', 'C', '文化与语用', 5, 6, '邮件礼仪', 'Email etiquette', 'moe-yy-2022:CU.L2', '了解英文邮件开头问候和结尾礼貌用语的基本规范。', '写一封简短的感谢邮件', '区分正式与非正式称呼'),
    e('vocabulary_notebook', 'M', '学习策略', 5, 6, '词汇积累本', 'Vocabulary notebook', 'moe-yy-2022:ST.L2', '能按主题整理新词并标注例句，定期复习。', '为本单元词汇建一页积累', '用新词各造一个例句'),
    e('reading_strategies_preview', 'M', '学习策略', 5, 6, '阅读预习策略', 'Reading preview', 'moe-yy-2022:ST.L2', '阅读前先浏览标题和图片，提出一到两个预测性问题。', '读前写出两个预测问题', '读后再核对预测'),
    e('self_assessment_checklist', 'M', '学习策略', 5, 6, '自评清单', 'Self-assessment', 'moe-yy-2022:ST.L2', '能对照学习目标清单自评听说读写掌握情况。', '完成单元自评表', '说出一项需加强的技能'),
    e('note_taking_while_listening', 'M', '学习策略', 5, 6, '听记关键词', 'Listening notes', 'moe-yy-2022:ST.L2', '听短文时能记录人名、数字等关键信息。', '听录音记录三个数字', '用关键词复述听力大意'),
    e('preview_review_cycle', 'M', '学习策略', 5, 6, '预习与复习', 'Preview and review', 'moe-yy-2022:ST.L2', '养成课前预习生词、课后复习课文的习惯。', '预习标注三个生词', '课后复述课文要点'),
    e('word_stress_patterns', 'L', '语音词汇语法', 7, 9, '单词重音', 'Word stress', 'moe-yy-2022:LK.L3.语音', '能在多音节词中识别并读出主要重音位置。', '标出comfortable的重音', '纠正重音读错的单词'),
    e('sentence_stress_intonation', 'L', '语音词汇语法', 7, 9, '句重音与语调', 'Sentence stress', 'moe-yy-2022:LK.L3.语音', '能运用一般疑问句升调和特殊疑问句降调，突出句中关键词。', '用升调朗读一般疑问句', '在句中重读信息词'),
    e('tense_consolidation', 'C', '语音词汇语法', 7, 9, '时态综合', 'Tense consolidation', 'moe-yy-2022:LK.L3.语法', '能在语篇中正确使用一般现在、过去、将来及现在进行时。', '在一篇短文中填空时态', '说明选用某时态的理由'),
    e('passive_voice_intro', 'C', '语音词汇语法', 7, 9, '被动语态入门', 'Passive voice intro', 'moe-yy-2022:LK.L3.语法', '能理解并运用一般现在时和一般过去时的被动语态基本结构。', '把主动句改为被动句', '在新闻标题中识别被动'),
    e('relative_clauses', 'C', '语音词汇语法', 7, 9, '定语从句', 'Relative clauses', 'moe-yy-2022:LK.L3.语法', '能用who、which、that引导的定语从句修饰名词。', '合并两个句子为含定语从句', '区分限定与非限定用法入门'),
    e('conditional_sentences', 'C', '语音词汇语法', 7, 9, '条件状语从句', 'Conditional clauses', 'moe-yy-2022:LK.L3.语法', '能使用if引导的真实条件句表达假设与结果。', '用If it rains…造句', '区分主将从现的用法'),
    e('modal_verbs', 'C', '语音词汇语法', 7, 9, '情态动词', 'Modal verbs', 'moe-yy-2022:LK.L3.语法', '能正确使用can、should、must等情态动词表达能力、建议和义务。', '用should给出建议', '区分must与have to语气'),
    e('discourse_cohesion', 'R', '语音词汇语法', 7, 9, '语篇衔接', 'Discourse cohesion', 'moe-yy-2022:LK.L3.语篇', '能识别however、therefore等连接词在语篇中的衔接作用。', '找出段落中的连接词', '选用合适连接词合并句子'),
    e('text_types_features', 'C', '语音词汇语法', 7, 9, '常见语篇类型', 'Text types', 'moe-yy-2022:LK.L3.语篇', '能区分记叙、说明、议论等语篇类型的基本特征。', '判断一篇短文属于何种类型', '列出说明文常见结构'),
    e('listen_news_brief', 'P', '听与说', 7, 9, '听新闻简报', 'Listening to news', 'moe-yy-2022:LS.L3', '能听懂英语新闻或校园广播中的主要信息。', '记录新闻中的时间地点', '概括一分钟新闻大意'),
    e('oral_presentation', 'P', '听与说', 7, 9, '口头报告', 'Oral presentation', 'moe-yy-2022:LS.L3', '能就熟悉话题做一到两分钟的英文口头报告。', '完成有开头结尾的口头报告', '回答听众一个问题'),
    e('debate_basics', 'P', '听与说', 7, 9, '辩论基础', 'Debate basics', 'moe-yy-2022:LS.L3', '能在辩论中陈述观点并用Firstly、However组织论述。', '就校园话题陈述立场', '回应对方论点'),
    e('interview_skills', 'P', '听与说', 7, 9, '采访技巧', 'Interview skills', 'moe-yy-2022:LS.L3', '能设计问题并采访同学，记录回答要点。', '完成一次双人英文采访', '提出至少三个开放性问题'),
    e('listen_lecture_notes', 'M', '听与说', 7, 9, '听讲座记笔记', 'Lecture note-taking', 'moe-yy-2022:LS.L3', '听较长讲话时能分层记录要点和细节。', '用提纲记录讲座结构', '根据笔记复述三个要点'),
    e('read_narrative_text', 'P', '读与看', 7, 9, '阅读记叙文', 'Reading narratives', 'moe-yy-2022:RV.L3', '能读懂记叙文并梳理人物、情节和主题。', '画出故事发展曲线', '回答关于人物动机的问题'),
    e('read_expository_text', 'P', '读与看', 7, 9, '阅读说明文', 'Reading expository texts', 'moe-yy-2022:RV.L3', '能读懂说明文并提取中心论点和支撑细节。', '找出说明文的主题句', '列出三个支撑细节'),
    e('inference_reading', 'M', '读与看', 7, 9, '推理阅读', 'Reading inference', 'moe-yy-2022:RV.L3', '能根据上下文和线索推断词义和隐含信息。', '推断生词在句中的含义', '说明推断依据'),
    e('read_poetry_basic', 'R', '读与看', 7, 9, '阅读简易诗歌', 'Reading poetry', 'moe-yy-2022:RV.L3', '能朗读英文短诗并感受节奏和意象的基本特点。', '朗读一首短诗注意节奏', '说出诗中一个意象'),
    e('critical_reading_intro', 'M', '读与看', 7, 9, '批判性阅读入门', 'Critical reading', 'moe-yy-2022:RV.L3', '能对短文观点提出疑问并区分事实与观点。', '找出一处作者观点', '提出一个不同看法'),
    e('essay_structure', 'R', '写', 7, 9, '议论文结构', 'Essay structure', 'moe-yy-2022:WR.L3', '了解英文议论文引言、主体段和结论的基本结构。', '为一篇作文列三段提纲', '写出含主题句的主体段'),
    e('argumentative_writing', 'P', '写', 7, 9, '议论文写作', 'Argumentative writing', 'moe-yy-2022:WR.L3', '能就熟悉话题写一百词左右的议论文并给出理由。', '完成一篇含正反观点的作文', '使用连接词组织论证'),
    e('report_writing', 'P', '写', 7, 9, '报告写作', 'Report writing', 'moe-yy-2022:WR.L3', '能根据调查结果写简短英文报告，含数据描述。', '写一份班级调查小报告', '用数字描述调查结果'),
    e('summary_writing', 'P', '写', 7, 9, '概要写作', 'Summary writing', 'moe-yy-2022:WR.L3', '能用自己语言概括短文大意，避免逐句翻译。', '将一段文字压缩为三句', '检查是否遗漏关键信息'),
    e('formal_email_letter', 'P', '写', 7, 9, '正式邮件与信函', 'Formal email', 'moe-yy-2022:WR.L3', '能撰写格式规范的正式邮件或申请信。', '写一封活动申请邮件', '使用恰当的开头和结尾'),
    e('global_citizenship', 'C', '文化与语用', 7, 9, '全球公民意识', 'Global citizenship', 'moe-yy-2022:CU.L3', '能讨论环境保护、公益等全球性议题的英语表达。', '用英语表达节约用水观点', '了解一项国际环保行动'),
    e('cross_cultural_communication', 'C', '文化与语用', 7, 9, '跨文化交际', 'Cross-cultural communication', 'moe-yy-2022:CU.L3', '了解不同文化在问候、送礼等方面的差异，避免误解。', '比较两种文化的餐桌礼仪', '举例说明文化误解'),
    e('media_literacy_english', 'C', '文化与语用', 7, 9, '英语媒体素养', 'Media literacy', 'moe-yy-2022:CU.L3', '能初步辨别英文网络信息来源并警惕谣言。', '判断一条英文信息是否可信', '说明验证信息的方法'),
    e('idioms_expressions', 'L', '文化与语用', 7, 9, '习语与惯用语', 'Idioms', 'moe-yy-2022:CU.L3', '能理解并适当使用break the ice等常见习语。', '猜测习语字面与引申义', '在对话中正确使用一个习语'),
    e('literature_appreciation', 'C', '文化与语用', 7, 9, '文学作品欣赏', 'Literature appreciation', 'moe-yy-2022:CU.L3', '能阅读简写版英文名著片段并讨论人物与主题。', '描述一位文学人物性格', '说出故事给你的启示'),
    e('autonomous_learning', 'M', '学习策略', 7, 9, '自主英语学习', 'Autonomous learning', 'moe-yy-2022:ST.L3', '能制定个人英语学习计划并选择合适资源。', '列出本周自主学习任务', '评价一种学习资源的效果'),
    e('error_analysis', 'M', '学习策略', 7, 9, '错题分析', 'Error analysis', 'moe-yy-2022:ST.L3', '能分析自己常犯的语言错误类型并针对性练习。', '归类五次语法错误', '制定一项改进措施'),
    e('learning_portfolio', 'M', '学习策略', 7, 9, '学习档案袋', 'Learning portfolio', 'moe-yy-2022:ST.L3', '能整理代表性作业和反思，展示学习进步。', '选取三份作品入档案', '写一段学习反思'),
    e('exam_strategies', 'M', '学习策略', 7, 9, '考试策略', 'Exam strategies', 'moe-yy-2022:ST.L3', '掌握听力预览、阅读先看题等应试技巧并合理分配时间。', '模拟考试规划答题顺序', '说明一项时间管理策略'),
    e('collaborative_learning', 'M', '学习策略', 7, 9, '合作学习与互评', 'Collaborative learning', 'moe-yy-2022:ST.L3', '能在小组中分工完成项目并互评同伴表现。', '完成小组英文海报项目', '按量规给同伴反馈'),
]

if __name__ == "__main__":
    from topiclib import dump
    dump("english.json", ENGLISH)
